name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: CityPharmacyChain                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: CityPharmacyChain/CityPharmacyChain.Tests                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ./CityPharmacyChain/CityPharmacyChain.Tests/CityPharmacyChain.Tests.csproj --no-build --verbosity normal
      
